# Generated by Django 2.0.9 on 2018-12-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.CharField(default='we', max_length=30),
            preserve_default=False,
        ),
    ]
